[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x', 'postgresql']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist',
  'npm ci',
]

[phases.build]
cmds = [
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
]

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
